#!/usr/bin/python3


def raise_exception_msg(message=""):
    """Raise a NameError with message."""
    message = printOut
    raise NameError(printOut)

